### ISSUE TITLE
Stream doesn’t not work for some tables

### ISSUE THREAD

**Issue by akram-95** [supabase-community/supabase-flutter#29] opened 2021-10-01 22:29 UTC
My Stream doesn't update the data for a table but for all others tables , it work 

That's the code for listening 

```dart
void _loaddata () {
  Supabase.instance.from("test").stream.execute().listen((Event){
    print(Event);
  });
  
  Supabase.instance.from("test1").stream.execute().listen((Event){
    print(Event);
  });
  
  Supabase.instance.from("test2").stream.execute().listen((Event){
    print(Event);
  });
}
```

I get real time changes from table test1 and test2 but not from table test .

**Comment by dshukertjr** [comment] 2021-10-03 01:16
@akram-95 
I assume you have turned on realtime by following the instruction described [here](https://supabase.io/docs/guides/api#managing-realtime), correct?

Is your table literally called `test`, or is it actually called something else in your real environment?

**Comment by akram-95** [comment] 2021-10-03 01:38
Yeah , it's enabled, and it work if I create a new instance of supabaseClient , no it's called something else

**Comment by bdlukaa** [comment] 2021-10-03 10:22
probably because the token is not refreshing properly

**Comment by akram-95** [comment] 2021-10-03 11:27
> probably because the token is not refreshing properly

Does it depend on my code to refresh the token properly?

**Comment by dshukertjr** [comment] 2021-10-03 12:45
@akram-95 
Could I ask you to follow the issue template when you open an issue next time and provide step by step instruction to reproduce your issue so that we can better find the cause? In the mean while, could you detailed steps of how you found this issue and minimal code to reproduce this issue if possible?

**Comment by akram-95** [comment] 2021-10-03 13:40
@override
  void initState() {

    _loadData();

    super.initState();
  }
void _loadData() async {
    _storiesSubscription = DatabaseHelper()
        .client
        .from('Stories')
        .stream()
        .execute()
        .listen((events) {
      print("events");
      if (events.isNotEmpty) {
        setState(() {});
      }
    });
    _profilesSubscription = supabaseController.instance
        .from('IndividualProfile')
        .stream()
        .execute()
        .listen((events) {
      if (events.isNotEmpty) {
        setState(() {});
      }
    });
    _commentsSubscription =  _profilesSubscription = supabaseController.instance
        .from('Comments')
        .stream()
        .execute()
        .listen((events) {
      if (events.isNotEmpty) {
        setState(() {});
      }
    });
  }

i can listen to changes in tables IndividualProfile and Comment but  not from table Stories
and sometimes when i reinitialize the supabaseClient i can do it

**Comment by bdlukaa** [comment] 2021-10-03 14:01
Have you tried
```dart
    _storiesSubscription = supabaseController.instance
        .from('Stories')
        .stream()
        .execute()
        .listen((events) {
      print("events");
      if (events.isNotEmpty) {
        setState(() {});
      }
    });
```
?

just like the others?

**Comment by akram-95** [comment] 2021-10-03 14:20
In this exemple it works because I create a new instance of supabaseController , in the case that I use the same instance , it doesn't work

**Comment by dshukertjr** [comment] 2021-10-03 22:27
@akram-95 
Could you provide a code sample that we can actually copy and paste and it will run, or if you have repo, could you paste a link to it?

**Comment by akram-95** [comment] 2021-10-03 22:40
> @akram-95 Could you provide a code sample that we can actually copy and paste and it will run, or if you have repo, could you paste a link to it?

i don't have a repo but i can send you the code

class StoriesView extends StatefulWidget {
  const StoriesView({Key? key}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return StoriesViewState();
  }
}

class StoriesViewState extends State<StoriesView> {
  late StreamSubscription _storiesSubscription;
  late StreamSubscription _profilesSubscription;
  late StreamSubscription _commentsSubscription;

  @override
  void initState() {
    controller1 = AutoScrollController(
        viewportBoundaryGetter: () =>
            Rect.fromLTRB(0, 0, 0, MediaQuery.of(context).padding.bottom),
        axis: scrollDirection);
    _loadData();

    super.initState();
  }

  late Future _profileFuture;

  void _loadData() async {
    _storiesSubscription = DatabaseHelper()
        .client
        .from('Stories')
        .stream()
        .execute()
        .listen((events) {
      print("events");
      if (events.isNotEmpty) {
        setState(() {});
      }
    });
    _profilesSubscription = supabaseController.instance
        .from('IndividualProfile')
        .stream()
        .execute()
        .listen((events) {
      if (events.isNotEmpty) {
        setState(() {});
      }
    });
    _commentsSubscription =  _profilesSubscription = supabaseController.instance
        .from('Comments')
        .stream()
        .execute()
        .listen((events) {
      if (events.isNotEmpty) {
        setState(() {});
      }
    });
  }

  @override
  void dispose() {
    super.dispose();
    _storiesSubscription.cancel();

    _profilesSubscription.cancel();
  }

  String trimCollapsedText = "Show more";
  String trimExpandedText = "Show less";
  String collapsedValue = "";
  final DatabaseHelper _databaseHelper = DatabaseHelper();
  final storiesController = Get.put(StoriesController());
  List<String> mentions = [];
  final TextEditingController _textController = TextEditingController();
  List<String> commentMentionsuserId = [];
  CommentController commentController =
      Get.put<CommentController>(CommentController(), tag: "Story");
  final SupabaseController supabaseController = Get.find<SupabaseController>();
  bool _needsScroll = false;
  final scrollDirection = Axis.vertical;

  late AutoScrollController controller1;

  bool checkBraces(String value) {
    if (value.isEmpty) {
      return true;
    }
    int count = 0;
    for (int i = 0; i < value.length; i++) {
      if (value.contains("https") && value[i] == "(") count++;
      if (value.contains("https") && value[i] == ")") count--;
      if (count < 0) return false;
    }
    return count == 0;
  }

  void _scrollToEnd(ScrollController controller) {
    if (!controller.hasClients) {
      return;
    }

    var scrollPosition = controller.position;

    if (scrollPosition.maxScrollExtent > scrollPosition.minScrollExtent) {
      controller.animateTo(
        scrollPosition.pixels + 2000,
        duration: new Duration(milliseconds: 200),
        curve: Curves.easeOut,
      );
    }
  }

 

  Future scrollToBottom(ScrollController scrollController) async {
    while (scrollController.position.pixels !=
        scrollController.position.maxScrollExtent) {
      scrollController.jumpTo(scrollController.position.maxScrollExtent);
      await SchedulerBinding.instance!.endOfFrame;
    }
  }

  @override
  Widget build(BuildContext context) {
    PreferredSize appbarWidget() {
      return PreferredSize(
        preferredSize: Size(Get.width, 120),
        child: Stack(
          children: <Widget>[
            Positioned(
                top: 50,
                left: 20.0,
                right: 20.0,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text(
                      "Stories",
                      style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 25,
                          color: Colors.indigo),
                    ),
                    Row(
                      children: [
                        IconButton(
                            onPressed: () {
                              Get.to(() => const MarkdownEditor());
                            },
                            icon: const Icon(
                              Icons.add_circle,
                              color: Colors.indigo,
                            )),
                        IconButton(
                            onPressed: () {},
                            icon: const Icon(Icons.notifications_outlined)),
                      ],
                    )
                  ],
                )),
            Positioned(
              // To take AppBar Size only
              top: 110,
              left: 20.0,
              right: 20.0,
              child: CupertinoSearchTextField(
                placeholder: "Suche",
                controller: storiesController.searchController,
                onChanged: (value) {
                  storiesController.setSearchValue(value);
                  setState(() {});
                },
                onSubmitted: (value) {
                  // setState(() {});
                },
              ),
            ),
          ],
        ),
      );
    }

    return StreamBuilder<List<Map<String, dynamic>>>(
        stream: supabaseController.instance
            .from("Stories")
            .stream()
            .order("timestamp")
            .execute(),
        builder: (context, snapshots) {
          if (!snapshots.hasData) {
            return const Center(child: CupertinoActivityIndicator());
          } else if (snapshots.hasError) {
            return Center(
              child: InkWell(
                child: const Text("something is wrong , try again"),
                onTap: () {
                  setState(() {});
                },
              ),
            );
          }
          List<Story> storyList =
              snapshots.data!.map((e) => Story.fromJson(e)).toList();

          return Scaffold(
            appBar: appbarWidget(),
            body: Column(
              children: [
                Expanded(
                  flex: 1,
                  child: ListView.builder(
                      itemCount: storyList.length,
                      itemBuilder: (BuildContext context, int index) {
                        return StreamBuilder<List<Map<String, dynamic>>>(
                            stream: _databaseHelper.client
                                .from(
                                    "IndividualProfile:userId=eq.${storyList[index].authorId}")
                                .stream()
                                .execute(),
                            builder: (context, profile) {
                              if (!profile.hasData) {
                                return const Center(
                                    child: CupertinoActivityIndicator());
                              } else if (profile.hasError) {
                                return Center(
                                  child: InkWell(
                                    child: const Text(
                                        "something is wrong , try again"),
                                    onTap: () {
                                      setState(() {});
                                    },
                                  ),
                                );
                              } else if (profile.data!.isEmpty ||
                                  storyList.isEmpty) {
                                return Container();
                              }
                              IndividualProfile individualProfile =
                                  IndividualProfile.fromJson(
                                      profile.data!.single);

                              return widgetCard(
                                  individualProfile, storyList[index]);
                            });
                      }),
                ),
              ],
            ),
          );
        });
  }

**Comment by dshukertjr** [comment] 2022-09-27 11:22
Sorry for not coming back to this for a long time. 

@akram-95 I noticed few things here. 

Is this a typo?
```dart
_commentsSubscription =  _profilesSubscription = supabaseController.instance
```

Another thing I noticed is that you seem to listen to the changes from the same table in multiple places within your app. In Supabase, you can only subscribe to the same table in one place, so you want to maybe create another file or something that listens to the updates, and create a stream that emits the changes. 

[Here](https://github.com/supabase-community/flutter-chat/blob/with_auth/lib/utils/messages_provider.dart) is an example of how you could do that.

**Comment by dshukertjr** [comment] 2022-09-28 03:45
I will close this issue for now as it seems like the issue was from listening to the same table change in multiple locations in the app. Please feel free to reopen this issue if the issue persists with the fix implemented.

**Closed by dshukertjr** 2022-09-28 03:45 UTC
Labels: bug, realtime
