### ISSUE TITLE
stream() method provides wrong duplicate data when update occurs

### ISSUE THREAD

**Issue by topperspal** [supabase-community/supabase-flutter#64] opened 2022-02-06 13:29 UTC
### Table
|id|name|requests|
|--|------|----|
|1| Aaa|1|
|2|Bbb|1|
|3|Ccc|1|

```dart
_client
      .from('users')
      .stream(['id'])
      .order('requests', ascending: true)
      .limit(50)
      .execute()
```

When I update some data in the users table, the stream provides three rows but not all three rows, It most probably return 3 rows which contains
1. The updated row with **updated** data
2. The updated row with **old** data
3. One of the remaining two rows

**Comment by dshukertjr** [comment] 2022-02-06 14:43
Thanks for opening this issue @topperspal . 

I am struggling to reproduce this issue at the moment. For example, with the sample data you have provided, what would the output be when you perform an update on let's say row 1?

**Comment by topperspal** [comment] 2022-02-06 16:53
I reviewed my code and found that the reason for this unexpected behavior is the empty array passed in `.stream([])`.

In my case, I use a composite primary key. This means none of my fields is unique so how I can use this.

Second I want to order data by two fields, requests and created_at, how I can achieve this.

**Comment by dshukertjr** [comment] 2022-02-08 22:12
@topperspal 
>In my case, I use a composite primary key. This means none of my fields is unique so how I can use this.

In that case, all you need to do is pass all of the primary key column names to `stream()` like this for example

```dart
.stream(['user_id', 'post_id'])
```

>Second I want to order data by two fields, requests and created_at, how I can achieve this.

We do not currently support sorting by multiple columns, but this is certainly something we can look into adding. Meanwhile, it might be a bit of a hassle, but you can write your own sorting function and apply that to the data you received from `stream()`.

**Comment by dshukertjr** [comment] 2022-09-27 13:25
Closing this as the cause of the original issue was found.

**Closed by dshukertjr** 2022-09-27 13:25 UTC
Labels: bug, realtime
