### ISSUE TITLE
Issues Noticed with Auth

### ISSUE THREAD

**Issue by Ashwaq3** [supabase-community/supabase-flutter#75] opened 2022-04-17 02:18 UTC
I have been working with auth via different methods.

1. JWT expired and the session lost 😩 I noticed it’s expired after the period written in Supabase which can be maximum 1 week. Wish if we can stay logged in until it’s logged out by the user Like instagram.

2. Provider sign in has to ways a. Sigin method which doesn’t lunch the url you have to lunch it by yourself b. SigninWithProvider which return bool 

both methods doesn’t return the session and don’t trigger onAuthStateChange 

3. Phone auth is cool but I would highly recommend if we can sign users with phone directly “ In my case Im using other sms provider api so I had to workaround and signup the user first”

Thanks and hope it will be fixed soon🔥

**Comment by DanMossa** [comment] 2022-04-17 03:15
1. I'm curious why the session isn't automatically being refreshed. Probably a bug that can be looked into.
2. There's a PR for signInWithProvider to return the correct value.

**Comment by Ashwaq3** [comment] 2022-04-17 03:29
@DanMossa 
Just checked your PR it would be amazing if it's fixed.

It could be in this way or any other way as long as it allowed me signin with phone without sigin it up.

**Comment by Ashwaq3** [comment] 2022-04-17 03:42
@DanMossa 
#73 as a way to fix the issue i can see you return the GotrueSessionResponse instead of bool "That's cool but still the response will return 2 things url and provider name.

I believe the main issue is in the _handleProviderSignIn here where the session should be given 
![image](https://user-images.githubusercontent.com/40840475/163699279-e935e746-7e6f-43db-9bee-1086ad42dde0.png)

**Comment by bdlukaa** [comment] 2022-04-17 11:46
1. #33

**Comment by bdlukaa** [comment] 2022-07-17 19:39
I guess we can close this a duplicate of the above issues

**Closed by bdlukaa** 2022-07-17 19:39 UTC
Labels: bug, auth
