### ISSUE TITLE
WidgetsBinding Error

### ISSUE THREAD

**Issue by fmcalado** [supabase-community/supabase-flutter#114] opened 2022-05-15 20:06 UTC
../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/supabase_flutter-0.3.1/lib/src/supabase_auth_required_state.dart:39:29: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially 
null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addObserver(this);
                            ^^^^^^^^^^^
../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/supabase_flutter-0.3.1/lib/src/supabase_auth_required_state.dart:45:29: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Downloads/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.removeObserver(this);
                            ^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

**Comment by DanMossa** [comment] 2022-05-15 20:14
Fix in #112

**Comment by dshukertjr** [comment] 2022-05-16 04:49
Thanks @fmcalado for opening this issue.

I have created a [PR](https://github.com/supabase-community/supabase-flutter/pull/116) to make sure we test the library against different versions of Flutter. In the meanwhile, you should be able to use an older version of the library or run `flutter upgrade` to get rid of the error. 

@DanMossa After merging #113, I thought it might be better to fix the root cause, and (after struggling with version conflicts) decided to cleanup the dependencies though out the sub libraries as well so that this library can be used in Flutter 2.0.0 and above.

**Comment by FatumaA** [comment] 2022-05-16 05:54
Running flutter upgrade solves the widget binding issue but not the launch url one 
<img width="1086" alt="Screenshot 2022-05-16 at 08 48 22" src="https://user-images.githubusercontent.com/67555014/168527606-1db2bac1-1c49-4eed-9a61-4a3b63305a47.png">

as referenced here #112 
Am I missing something?

**Comment by dshukertjr** [comment] 2022-05-16 06:36
@FatumaA Right, sorry for this one as well. If you could try to delete your `pubspec.lock` file and re-run `flutter pub get`, I think this error will go away as well. Please let me know if that doesn't work either.

**Comment by FatumaA** [comment] 2022-05-16 06:45
@dshukertjr worked 😌 Thank you!

**Comment by Mause** [comment] 2022-05-18 08:11
Do you know when you'll have a new version out with these fixes?

**Comment by dshukertjr** [comment] 2022-05-18 14:53
@Mause We are aiming to release a fix in the next few days. Thank you for your patients.

**Comment by dshukertjr** [comment] 2022-06-17 01:13
This was fixed on `v0.3.1+1`

**Closed by dshukertjr** 2022-06-17 01:13 UTC
