### ISSUE TITLE
signInWithProvider returns bool where as signIn returns GotrueSessionResponse

### ISSUE THREAD

**Issue by Shiba-Kar** [supabase-community/supabase-flutter#72] opened 2022-03-30 18:08 UTC
```
Future<GotrueSessionResponse> signIn({
  String? email,
  String? phone,
  String? password,
  Provider? provider,
  OpenIDConnectCredentials? oidc,
  AuthOptions? options,
})
```

```
Future<bool> signInWithProvider(Provider provider, {AuthOptions? options})
```
as signInWithProvider returns bool , cant get the Session from it.

**Comment by DanMossa** [comment] 2022-03-30 18:31
Good catch. We should be returning the result of `signIn` and not `launch`

**Comment by DanMossa** [comment] 2022-03-30 20:06
Fixed in #73

**Comment by jstnw10** [comment] 2022-07-05 09:14
Workaround until it is fixed in latest release: Use something like uni_links and catch deeplinks. Parse the refresh_token manually and call `setSession()` method.

**Comment by dshukertjr** [comment] 2022-09-29 07:00
Closing this issue as this is actually by design. Because provider sign in relies on opening an webview and coming back to the app via deeplinks, there is no way for the method to return the result of the sign in. Whether the sign in went through or not should be determined by listening to `onAuthStateChanged` callback!

**Closed by dshukertjr** 2022-09-29 07:00 UTC
Labels: auth
