### ISSUE TITLE
`signUp` creates an account but throws an exception

### ISSUE THREAD

**Issue by caseycrogers** [supabase-community/supabase-flutter#182] opened 2022-08-11 19:16 UTC
If you call `signUp` with `supabase_flutter 1.0.0-dev.3` and email verification required, it creates the account but throws an error:

```dart
await supabase.auth.signUp(email, password);
```

```
GoTrueException(message: An error occurred on sign up., statusCode: null)
      #0      GoTrueClient.signUp (package:gotrue/src/gotrue_client.dart:76:7)
      <asynchronous suspension>
      #1      AuthManager.createUser.<anonymous closure> (package:cast_me_app/business_logic/clients/auth_manager.dart:69:9)
      <asynchronous suspension>
      #2      _authActionWrapper.<anonymous closure> (package:cast_me_app/business_logic/clients/auth_manager.dart:218:5)
      <asynchronous suspension>
```

It looks like the client assumes a response with `null` data means an error when the server is sending null on success:
```dart
if (response.data == null) {
  throw GoTrueException('An error occurred on sign up.');
}
```

iirc returning null is expected behavior for sign up if email verification is required because the server can't sign you in until after you've verified your email?

**Comment by caseycrogers** [comment] 2022-08-11 19:23
Related comment:
the current auth flow is as follows:
1) create account -> still not signed in
2) verify email -> still not signed in
3) call `signIn` -> finally signed in

It's not a big deal, but I'd dramatically prefer it if the flow were as follows:
1) create account -> signed in, but user session is in a demoted state
2) verify email -> signed in, user session is promoted to standard level

The following is much preferred because:
- I don't have to make the extra server call to sign in the user
- If the user exits and reopens without having completed email verification, I can have them click sign up without sign up throwing an exception, I can simply catch that the user session isn't fully promoted
- I can easily provide partial access to app features for accounts that haven't completed email verification to make the sign up experience lower friction (eg you can view content, but can't post)

Happy to file a separate issue for this if that'd be helpful

**Comment by Vinzent03** [comment] 2022-08-11 19:27
I think the issue is that we require a session after signup, but a session is not returned when verify email is turned on. https://github.com/supabase-community/gotrue-dart/blob/02f0b3d1411eff5c190081e94946d2be291421ff/lib/src/gotrue_client.dart#L75
@dshukertjr 
I'm unsure what the exact flow should be with email verification. When no session is returned we don't fire an sign in event, right? https://github.com/supabase-community/gotrue-dart/blob/02f0b3d1411eff5c190081e94946d2be291421ff/lib/src/gotrue_client.dart#L80

**Comment by Vinzent03** [comment] 2022-08-11 19:51
I see now it's a duplicate of #173. I'm closing the other one since here is more info.

**Comment by dshukertjr** [comment] 2022-08-12 07:50
@Vinzent03 
Sorry for the late response here. 

>I'm unsure what the exact flow should be with email verification. When no session is returned we don't fire an sign in event, right?

Yup, that should be correct!

>In addition, shouldn't the session parameter be called session instead of data?

Great call! Right now is the time to introduce these breaking changes, so let's get it in as well!

**Closed** 2022-08-12 08:32 UTC
Labels: bug, auth

**Comment by caseycrogers** [comment] 2022-08-18 09:21
I'm curious if you all have any thoughts on my proposed restructuring of auth flow where `signUp` with email verification enabled signs the user in but in a probationary state?
