### ISSUE TITLE
Cannot filter in anyway

### ISSUE THREAD

**Issue by vietlinhtspt** [supabase-community/supabase-flutter#194] opened 2022-08-21 10:26 UTC
supabase_flutter: ^1.0.0-dev.4
I am using filter to query data in some ways:

column: table name ex: 'title'.
value: List of String: ['title'].

await Supabase.instance.client
.from(table)
.select()
.contains(column, value);

await Supabase.instance.client
.from(table)
.select()
.filter(column, 'cs', value);

It always throw an error: Unhandled Exception: PostgrestException(message: operator does not exist: text @> unknown, code: 42883, details: Not Found, hint: No operator matches the given name and argument types. You might need to add explicit type casts.)

Can anyone help me?

**Comment by Vinzent03** [comment] 2022-08-21 11:03
Duplicate of #196

**Closed** 2022-08-21 11:04 UTC
