### ISSUE TITLE
Korean characters in user metadata not shown properly

### ISSUE THREAD

**Issue by MythologyJH** [supabase-community/supabase-flutter#212] opened 2022-09-08 03:01 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Version [e.g. 1.0.0-dev.4]

**Additional context**

<img width="481" alt="스크린샷 2022-09-08 11 51 50" src="https://user-images.githubusercontent.com/77431993/189023962-38f6c73e-2542-4a83-84aa-6bdcc555c4af.png">

When you receive raw data from fetch, Korean is broken.
Please check it out.

**Comment by dshukertjr** [comment] 2022-09-08 12:58
Hi @MythologyJH,

Thanks for opening the issue. If you could follow the issue template and provide steps to reproduce the issue we will be happy to take a look at it! 

Supabase uses UTF8 for character encoding, so there should not be any problem handling Korean.

**Comment by MythologyJH** [comment] 2022-09-08 13:14
> 안녕@MythologyJH,
> 
> 문제를 열어주셔서 감사합니다. 문제 템플릿을 따르고 문제를 재현하기 위한 단계를 제공할 수 있다면 기꺼이 살펴보겠습니다!
> 
> Supabase는 문자 인코딩에 UTF8을 사용하므로 한국어를 처리하는 데 문제가 없습니다.

Oh! Come to think of it, I put the value in the user data when I joined the membership, and I think I was there in the process. There is no problem importing. I'm sorry

**Comment by dshukertjr** [comment] 2022-09-09 03:02
@MythologyJH Great to hear that everything seems to be fine! I will close this issue, but let us know if you are ever facing any issues with supabase-flutter!

**Comment by MythologyJH** [comment] 2022-09-13 01:19
@dshukertjr 

Can you take a look at this?

The meta value inside the userData in the database of Supabase showed Korean normally.

But if you keep bringing it, it's broken, and I looked for what the problem was, and there was a problem with the fetch inside GoTrue_Api.

As shown in the picture below, the json.decode (response.body) is received

final body = utf8.decode(response.bodyBytes);
final jsonBody = json.decode(body);

When I did it in the form, the Korean alphabet was not broken.

Just in case, I would appreciate it if you could check the fetch class again.


<img width="373" alt="스크린샷 2022-09-13 10 13 25" src="https://user-images.githubusercontent.com/77431993/189785854-ebee4ebf-7ab0-4406-aed6-d225a782cd85.png">


<img width="302" alt="스크린샷 2022-09-13 10 13 14" src="https://user-images.githubusercontent.com/77431993/189785846-4bec8672-7479-45c4-b0cb-98faba0a159b.png">

**Comment by dshukertjr** [comment] 2022-09-13 01:23
@MythologyJH thanks for looking into this.

Could you come up with a step by step instructions on how I could reproduce this?

**Comment by MythologyJH** [comment] 2022-09-13 01:48
**use package version**

`supabase: ^0.3.6`
`supabase_flutter: ^0.3.3`

---

**the reproduction process**

1. Enter the value of the user's metadata
(Nickname, name)
2. Enter the user's account information.
(email, password)
3. Sign up for e-mail membership.
4. After obtaining email authentication, proceed with email login.
5. If the login is successful, the user model is received from the session and stored inside the UserProvider.

    `var response = Constants.sessionClient.auth.user();`
    `return response;`
     The value is obtained from the provider and stored separately by email and metadata.

6. Open the drawer to display the user's information.

    `Map<String, dynamic> userData = context.select((UserProvider value) => value.userData);`
     ex) userData['nickname']

---

**Solution**

This will allow you to proceed with the corresponding error process.

The solution is just to add one line and change it like the code below

     `final body = utf8.decode(response.bodyBytes);`
     `final jsonBody = json.decode(body);`
Change it like this and put it in rawData

@dshukertjr here

**Closed** 2022-09-14 01:06 UTC
Labels: bug
