### ISSUE TITLE
The authenticated user get logout after a hour

### ISSUE THREAD

**Issue by iampopal** [supabase-community/supabase-flutter#33] opened 2021-10-05 18:44 UTC
# Authentication Bug
If user is not connected to internet and open app after a hour or two, the supabase.auth.user is null so the app show the login screen to user again. 

## To Reproduce

1. Run the quick start example 
2. Close the app 
3. Open app after hour or two with no internet connection
4. The supabase.auth.user which is current user will be null

**Comment by bdlukaa** [comment] 2021-10-05 18:49
did you `await` when calling `Supabase.initialize`?

**Comment by iampopal** [comment] 2021-10-07 19:13
Yes i do await 
And my main function has async

**Comment by iampopal** [comment] 2021-10-07 19:14
This issue happens after couples hours of login when u not has internet

**Comment by phamhieu** [comment] 2021-10-08 04:00
> Just run the simple
Login
Then force close the app
...
After 2 hours
Close your wifi or mobile data
Then open app again.

> Issue is that
supabase.auth.currentUser is null after couples hours of having no internet connection

The library works as it should be. When you turn on the app again, the library will try to refresh user session if it expired. If the device is offline, then refresh token will fail and user is log out.

@iampopal what's your expectation when the device is offline and user session is expired ?

**Comment by iampopal** [comment] 2021-10-08 05:22
The JWT shall Expire as it normally do 
But what I want is that after expiration of JWT 

supabase.auth.currentUser 

Shall not return null.

**Comment by iampopal** [comment] 2021-10-08 05:32
Like 
Whatsapp and Telegram or other social media apps 

They never logout us when we get offline 

The user session shall be saved and user shall not logout even the jwt expires

**Comment by KirioXX** [comment] 2022-01-18 18:26
We see a similar behaviour even when the app is open all the time.
It seems like the automatic token refresh is not happening.

Would it be possible to at least make the token refresh available via the API to let the client manually refresh the token when it is expired? Even better would be if the expire behaviour could be configured on the initialization.

**Comment by Jay-flow** [comment] 2022-01-25 09:55
How can I renew the expired jwt token?
I checked that there is `session.refreshToken`, but it seems to be related to social login.
Am I right?

**Comment by Jay-flow** [comment] 2022-01-25 09:57
> We see similar behaviour in production mode even when the app is open all the time. It seems like the automatic token refresh is not happening.
> 
> Would it be possible to at least make the token refresh available via the API to let the client manually refresh the token when it is expired? Even better would be if the expire behaviour could be configured on the initialization.

I found the API.
```dart 
await supabase.auth.api.refreshAccessToken(refreshToken);
```
But I don't know where to get the refresh token.

**Comment by Jay-flow** [comment] 2022-01-26 08:29
I confirmed that when the app is running, Supabase automatically refreshes the token.
However, when the app is turned off and then expired, the session returns a null value.
I think the app should be turned on again and Supabase should process the process to get a new token, but this doesn't happen automatically.

I wonder what we think about this.
If Supabase does not automatically receive a new token, I would like to know how to do this manually.

**Comment by KirioXX** [comment] 2022-01-28 08:20
@Jay-flow great find! I agree it would be great if supabase refreshes the token after opening the app.
We for example have devices that need to stay logged in 
because the user doesn't have the auth credentials and has to call an operator every time he gets logged out.

At the moment we hard refresh the token with this API on all server interactions:
```dart
Supabase.instance.client.auth.refreshSession();
```
but we already had some scenarios where this fails too.

**Comment by Jay-flow** [comment] 2022-01-30 10:44
@KirioXX Thx for leaving comments. That's right. As you know, It's not a perfect solution. This is because if the user does not access the app for a long time, the method will fail. Better measures are needed for this. If anyone shares a good idea about this, it will help everyone. :)

**Comment by christrunk** [comment] 2022-04-19 16:27
Just to add our own experience here:

### Scenario:

- Flutter app is used in a factory setting, Android and iOS devices
- Devices are used 7am-4pm, then left on charge each night
- During the day, the app is left idle 3 hours at most
- The factory has decent Wifi, but not perfect

### Summary

- We find that out of 70 active devices, 1-2 get logged out each week since we deployed mid-January this year
- It doesn't seem to correlate with the length of service (time elapsed since the device was first used) or idle time (time elapsed since the device was last used)


### Examples

**First occurrence:**
Was found logged out at 4.10pm
The device was last used around 4.00pm to clock out at the end of shift
The device has been in service just over 7 days

**Second occurrence:**
Was reported as logged out at 2pm
Was last used at lunchtime when coming back from break at 12pm
The device had been in service 10 days

**Third occurrence:**
Device was reported logged out at 8:40am
Was last used at 7:00am that day
The device had been in service approx 9 days

**Fourth occurrence:**
Device was reported logged out at 9:31am
Was last used at 7:10am on the same day
The device had been in service 7 days

Whilst these all seem to be getting logged out at around 7-10 days of service, there are likely 40-50 devices that have NEVER been logged out in 80 days of service.

**Comment by dshukertjr** [comment] 2022-04-22 13:53
@christrunk @KirioXX Thank you for providing additional details on this issue. This issue is the next issue we will tackle, and we hope to ship a fix sometime next week. We apologize for the inconvenience we have caused.

**Comment by caseycrogers** [comment] 2022-08-09 17:14
I'm getting this issue. However, in my case, neither user nor session are null. Was the above merged PR supposed to resolve this?

Here are my thoughts:
1) Supabase client should handle all this under the hood so I don't have to think about it
2) If there's a reason the client can't refresh the token under the hood, that should be reflected somehow in the client's state so I can catch it and handle it appropriately before attempting a failed server call. eg maybe add a `hasValidToken` flag to the auth client and call the auth state change callback whenever this flag changes.

**Comment by bdlukaa** [comment] 2022-08-09 17:20
> neither user nor session are null

@caseycrogers could you explain this?

**Comment by caseycrogers** [comment] 2022-08-09 17:32
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Supabase.initialize(
    url: '<snipped for brevity>',
    anonKey: '<snipped for brevity>',
  );
  print(Supabase.instance.client.auth.currentUser); // instance of 'User'
  print(Supabase.instance.client.auth.currentSession); // instance of 'Session'
  final dynamic result =
      await Supabase.instance.client.from('profiles').select(); // crashes with jwt expired error
  runApp(MyApp());
}
```

The error does not seem consistent. Just now I re-ran the above and it did not crash. Perhaps sometimes the client is failing to refresh the JWT token and other times it is not?

**Comment by bdlukaa** [comment] 2022-08-09 17:41
It'd be awesome if you could post the crash error and stacktrace in here

**Comment by caseycrogers** [comment] 2022-08-09 19:15
Error: `PostgrestException(message: {"code":"PGRST301","details":null,"hint":null,"message":"JWT expired"}, code: 401, details: Unauthor`

StackTrace:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PostgrestException(message: {"code":"PGRST301","details":null,"hint":null,"message":"JWT expired"}, code: 401, details: Unauthorized, hint: null)
#0      PostgrestBuilder._parseResponse (package:postgrest/src/postgrest_builder.dart:251:7)
<asynchronous suspension>
#1      PostgrestBuilder.then (package:postgrest/src/postgrest_builder.dart:327:24)
<asynchronous suspension>
```

**Comment by caseycrogers** [comment] 2022-08-12 22:56
I've realized that this only happens on my emulator and only happens when the emulator time is out of sync and behind the real time so I'm presuming that's the issue!

**Comment by dshukertjr** [comment] 2022-09-30 06:32
I will close this issue as we have implemented a retry for when when the client is offline and fails to refresh the token.

**Closed by dshukertjr** 2022-09-30 06:32 UTC
Labels: bug, auth

**Comment by zcmgyu** [comment] 2024-12-14 15:21
After all, I decided to leave Supabase though my application went live already.

**Comment by Vinzent03** [comment] 2025-05-27 20:02
@khordoo This is a really old closed issue. Please open a new issue with more details about your situation by following the bug report template.
