### ISSUE TITLE
Reset code for Email works correctly only for the first time. 

### ISSUE THREAD

**Issue by iampopal** [supabase-community/supabase-flutter#53] opened 2021-12-05 12:17 UTC
# Reset code for Email

I have my own website host at supabase settings page, when I reset password supabase send me an email.  When I click on the email Reset Passworkd link for the first time for every new email it works fine, but for the second or 3th time when I send reset link to email and click on the link sended to email I get error as 

https://myHost.com/#error_code=404&error_description=User+not+found

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a supabase project and disable email conformation
2. Create a simple app with 2 Button 1) Sign Up and 2) Forget password
2. on 1st Button Sign up call this:  auth.signIn(email: email, password: password)
3. on the 2nd button Forget the password call this:  auth.api.resetPasswordForEmail(email)
4. For the first time forget the password will work. on the second and 3rd time, it will not work.

**Comment by iampopal** [comment] 2021-12-07 06:54
Any update on this...

**Comment by dshukertjr** [comment] 2022-09-30 06:51
I cannot reproduce this with the current state, but do you still see this issue?

**Comment by iampopal** [comment] 2022-10-11 07:28
We have solve this issue with creating a website for reset password

**Comment by dshukertjr** [comment] 2022-10-11 08:39
@iampopal 
Thanks for the info. Going to close this issue as I could not reproduce it with the current version!

**Closed by dshukertjr** 2022-10-11 08:39 UTC
Labels: bug, auth
