### ISSUE TITLE
Missing or Invalid Credential after being 'Google Sign In' authenticated.

### ISSUE THREAD

**Issue by waihanko** [supabase-community/supabase-flutter#133] opened 2022-07-01 05:24 UTC
When I implement "Google Sign In" in my flutter app, deep link URL working fine, and it also created **user** in Supabase Users table successfully.
But, when redirect back to my app after authenticated, response always  show ''Missing or Invalid Credentials" and working `onErrorAuthenticating(response.error!.message);`  in supabase library's  `SupabaseAuthState` class.

**Comment by dshukertjr** [comment] 2022-07-01 07:40
@waihanko Thank you for reporting this issue. In this case, are you not signed in on your Flutter application after coming back to the app via deeplink?

**Comment by waihanko** [comment] 2022-07-01 10:34
> @waihanko Thank you for reporting this issue. In this case, are you not signed in on your Flutter application after coming back to the app via deeplink?

Yes, it never goes to `onAuthenticated` callback after coming back. when I debug, response message is "Missing or Invalid Credentials".

**Comment by dshukertjr** [comment] 2022-07-06 06:49
Hmm, thanks for the details. I will try to reproduce this one.

**Comment by waihanko** [comment] 2022-07-08 02:41
I tried on Android OS and device is MI9SE.
I will provide my sample repo link.

[https://github.com/waihanko/supabase_play_ground](supabase auth)

**Comment by dshukertjr** [comment] 2022-07-08 08:59
@waihanko 
Thank you for the sample repo! Let me try it on an Android device!

**Comment by dshukertjr** [comment] 2022-07-09 08:09
@waihanko 
So I did some investigations, and I was able to find out that the cause seem to be your Supabase instance. 

I swapped the credential on your sample app with mine, and I was able to login properly. Here is the credential that I used. 

```dart
    url: 'https://nlbsnpoablmsxwkdbmer.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyOTE5ODEwMiwiZXhwIjoxOTQ0Nzc0MTAyfQ.XZWLzz95pyU9msumQNsZKNBXfyss-g214iTVAwyQLPA',
```

I am not sure if this is some kind of misconfiguration, or a bug on the Supabase's end, but I might try to start a fresh Supabase project. If you must keep your current project, or want to further investigate the root cause of this problem, you can contact Supabase support at `support@supabase.io`!

I will close this issue as it does not seem like a issue with supabase_flutter, but please feel free to report anything that might come up!

**Closed by dshukertjr** 2022-07-09 08:09 UTC
Labels: auth
