### ISSUE TITLE
Removing Subscriptions Does Not Remove Channels/Subscriptions

### ISSUE THREAD

**Issue by alig1882** [supabase-community/supabase-flutter#130] opened 2022-06-14 17:22 UTC
After creating a few subscriptions similar to the following
```dart
final client = SupabaseClient(supabaseUrl, supabaseKey);

final subscription = client.from('mytable').on(SupabaseEventTypes.insert,(payload) {
// do something
}).subscribe();
```
Then removing the subscriptions later on with the client does not actually remove them. The reason I say this is that I can do
```dart
client.removeAllSubscriptions(); 
client.getSubscriptions().length; // should be equal to 0 now but in reality it's equal to the number of subscriptions created earlier
```

Then when I create new subscriptions without restarting the session, the number of subscriptions keeps going up. So removing all subscriptions does not actually accomplish anything.

Let me know if there is any other information I can provide that would be helpful.

**Comment by dshukertjr** [comment] 2022-06-15 08:16
@alig1882 Thanks for reporting this! We will take a look.

**Comment by zoocityboy** [comment] 2022-06-18 12:33
@alig1882 from my point of view this is not a bug. ```getSubscriptions()``` will return all subscriptions, even those closed but not yet removed. if you want to list active subscriptions, you should use filter
```dart
client.getSubscripton().where((subscription)=> !subscription.isClosed()).toList()
```

**Comment by alig1882** [comment] 2022-06-18 15:26
Thank you very much for this important clarification! I certainly was not aware of this. Can the documentation be updated then to reflect this? From what I understood from the documentation the method removeSubscription should be removing the subscription (as the name implies)

"Closes and removes all subscriptions and returns a list of removed subscriptions and their errors."
https://supabase.com/docs/reference/javascript/removeallsubscriptions

"Removes an active subscription and returns the number of open connections."
https://supabase.com/docs/reference/dart/removesubscription

"Closes and removes a subscription and returns the number of open subscriptions."
https://supabase.com/docs/reference/javascript/removesubscription

In the above you see both closing and removing the subscription.

**Comment by zoocityboy** [comment] 2022-06-18 18:27
I prepared a Pull Request that changes the return values of the remove function to match the supabase-js client library and avoid misunderstandings. [PR](https://github.com/supabase-community/supabase-dart/pull/118) 
@dshukertjr @alig1882

**Comment by dshukertjr** [comment] 2022-07-11 23:17
Closing this as it is fixed thanks to @zoocityboy 🎉

**Closed by dshukertjr** 2022-07-11 23:17 UTC
Labels: bug, realtime
