### ISSUE TITLE
Login/Signup on web not working

### ISSUE THREAD

**Issue by fabios9702** [supabase-community/supabase-flutter#163] opened 2022-08-03 12:46 UTC
I'm using supabase for my flutter app, and I've started the web app, the problem is that when I login (with magic link or provider) the user is not authenticated and if I refresh the page there is the error 'no access_token detected', I've tried also to download your flutter project and run on web, and I ha the same Issue.

I'm not passing redirect url to the Auth option.

**Comment by dshukertjr** [comment] 2022-08-03 12:51
Hi @fabios9702,

Thank you for opening this issue. Are you using the supabase-flutter 1.0.0-dev.1 or dev.2 version?

**Comment by fabios9702** [comment] 2022-08-03 12:53
@dshukertjr I'm using the latest stable release, supabase_flutter 0.3.3

**Comment by dshukertjr** [comment] 2022-08-03 12:56
@fabios9702 Thanks for letting me know! Would you be able to provide a simple code that you have written to reproduce this?

**Comment by fabios9702** [comment] 2022-08-03 13:03
@dshukertjr Basically when I tap on the button I call this function that sends the magic link to my email:

` await supabase.auth.signIn(
          email: emailController.text ,
          options: AuthOptions(
              redirectTo: kIsWeb
                  ? null
                  : 'io.supabase.flutterquickstart://login-callback/'));`

When I open then link with chrome, where the web app is running, it opens a new blank page, if I refresh the initial page I have the error

**Comment by dshukertjr** [comment] 2022-08-03 13:45
@fabios9702 
On your login page, are you using `SupabaseAuthState` class? Also, you mentioned that when you refresh the initial page, it does the user is not signed in, but it is signed in on the page that was opened by clicking the link in the email?

**Comment by fabios9702** [comment] 2022-08-03 13:52
@dshukertjr 
Yes I'm using the `SupabaseAuthState`, in fact in the mobile app everything works fine. When I refresh the pages, in both pages the the AuthState calls the `onAuthenticated()` function, but then there is the error of  `no access_token `

**Comment by fabios9702** [comment] 2022-08-03 14:20
@dshukertjr 
I've tried also with the code of supabase flutter

**Comment by dshukertjr** [comment] 2022-08-03 14:32
@fabios9702 Is it this one that you tried?
https://supabase.com/docs/guides/with-flutter

**Comment by fabios9702** [comment] 2022-08-03 14:37
yes, and I've downloaded this repository

**Comment by dshukertjr** [comment] 2022-08-04 05:15
@fabios9702 
I was able to reproduce this as well. There might be some issues on the stable version used with Flutter web. A lot of the APIs on the stable version will be old pretty soon, so would you want to test out the new version of supabase-flutter?

Here is the same example app built using the new SDK:
https://github.com/supabase-community/supabase-flutter-quickstart/tree/next

**Comment by fabios9702** [comment] 2022-08-04 15:04
@dshukertjr 

I've tried with the supabase_flutter 1.0.0-dev.2 version and has the same behavior

**Comment by deliqs** [comment] 2022-08-04 19:00
I had the same problem. My problem was caused by incorrect settings in the Authentication section in the Supabase dashboard. 

What URL do you receive when you log in? I had something like HOSTNAME/#/23%access_token. This way the query parameter for the access_token was 23%access_token and not access_token.

**Comment by dshukertjr** [comment] 2022-08-05 08:01
@fabios9702 
Are you able to create a loom video or something to describe what exactly is happening? I can't seem to reproduce it with the newest SDK. 

Did you try this one?
https://github.com/supabase-community/supabase-flutter-quickstart/tree/next

**Comment by deliqs** [comment] 2022-08-05 14:19
@dshukertjr 

I mistakenly followed _parts_ of the suggestions [here](https://github.com/supabase-community/supabase-flutter/issues/1).
So I added a redirect url that was something like "example.tld/%23". I didn't add any path after that. This causes the login to redirect to something like "example.tld#/%23access_token.....".

Supabase's uri parser for deep linking then saw %23access_token as a query parameter. So it failed to parse the value, hence "no access_token detected". My fix was removing the "/%23" part of the redirect url. I assume @fabios9702 has something similar.

**Comment by fabios9702** [comment] 2022-08-05 14:41
@deliqs I've tried but I have still the same Issue.

@dshukertjr here is the video of the behavior that I have. Sorry for the quality but I had to compress it.

https://user-images.githubusercontent.com/34335189/183100651-e47a6b7d-721e-41ee-ab14-02ccb8017d0f.mp4

**Comment by dshukertjr** [comment] 2022-08-06 05:25
@fabios9702 Could I take a look at the source code of this project? If not, could you try it with [this](https://github.com/supabase-community/supabase-flutter-quickstart/tree/next) one and see if it works? Could you record it and share it if it does not work either?

**Comment by fabios9702** [comment] 2022-08-08 16:31
@dshukertjr 
Unfortunately the problem is still there, I've already tries with the link you provided.

**Comment by PcolBP** [comment] 2022-08-10 14:08
Removing hash from url helps me, try it [here](https://docs.flutter.dev/development/ui/navigation/url-strategies)

**Comment by fabios9702** [comment] 2022-08-19 12:53
I've also tried also to remove the hash, but the problem is still there

**Comment by fabios9702** [comment] 2022-08-19 13:00
@PcolBP where did you remove the has? from the html file, from redirect url passed int he su-abase function or in the su-abase console?

**Comment by PcolBP** [comment] 2022-08-19 13:08
I removed hash by using this package https://pub.dev/packages/url_strategy give it a try.

**Comment by fabios9702** [comment] 2022-08-23 10:49
@PcolBP have you set some configuration, I've added the function `setPathUrlStrategy();` to main, but there is always the hash in the url and so is not working

**Comment by PcolBP** [comment] 2022-08-23 11:02
@fabios9702 are you using some route package or something? Navigator 1.0, 2.0? Tell more info about your setup. 

In my project I do use auto_route which is based on navigator 2.0. Haven't setup anything else.

**Comment by PcolBP** [comment] 2022-08-23 11:23
@fabios9702 So u're not using MaterialApp.router or anything like that related to Navigator 2.0 - .router?

**Comment by fabios9702** [comment] 2022-08-23 11:58
@PcolBP  ok, thanks, I'll try with the one you are using, auto_route, and let you know, thanks for the help :)

**Comment by PcolBP** [comment] 2022-08-23 12:04
@fabios9702 I think that better choice would be [go_router](https://pub.dev/packages/go_router) since it doesn't require build_runner so that save your time with every build. And it's maintained by flutter right now.  Whatsoever in go_router you can set up out of box pathStrategy like below:
![image](https://user-images.githubusercontent.com/67896443/186153262-d974c16f-9a93-4dce-a0d4-bb6cfbe6f0f8.png)

So no need for implementing another package.

**Comment by fabios9702** [comment] 2022-08-25 08:56
@PcolBP I've tried with go_router, but the problem is still there

**Comment by PcolBP** [comment] 2022-08-25 22:55
Which version of package are you using? I'm asking because I've delivered app with auth on the latest dev release => 1.0.0-dev.4 @fabios9702

**Comment by fabios9702** [comment] 2022-08-26 08:31
@PcolBP I've tried with the stable 4.2.9

**Comment by PcolBP** [comment] 2022-08-28 14:06
@fabios9702 I'm asking about supabase version.

**Comment by fabios9702** [comment] 2022-08-28 15:23
@PcolBP ah ok, BTW I'm using the last stable version of supabase. I'll try with the dev one

**Comment by fabios9702** [comment] 2022-08-30 09:12
@PcolBP I've tried, but it's still not working. I don't know what to try next. @dshukertjr do you know if there are any other solution or if it's a known supabase problem that needs to be solved at this point? I'm blocked with the web part of the app because of this

**Comment by dshukertjr** [comment] 2022-08-30 16:08
@fabios9702 Just in case it's a backend issue, would you be able to create a new Supabase project and see if the same issue persists? If it does, would you be able to share a minimal code to reproduce this issue?

**Comment by fabios9702** [comment] 2022-08-31 06:47
@dshukertjr  Seems that I solved the problem, now the login it's working I'll let you know if there will be other problems.

Thanks 😊

**Comment by PcolBP** [comment] 2022-08-31 06:54
@fabios9702 could you share solution with us?

**Comment by dshukertjr** [comment] 2022-09-01 03:19
@fabios9702 Glad to hear that it has been resolved. If I understand it correctly, you didn't change any of your code, but it started working properly? I apologize if it was a server issue. 

For now, I would close this issue!

**Closed by dshukertjr** 2022-09-01 03:19 UTC
Labels: auth

**Comment by fabios9702** [comment] 2022-09-01 07:07
@dshukertjr Correct, thanks 😁
