### ISSUE TITLE
Updating data returns an empty Exception when there is no results returned

### ISSUE THREAD

**Issue by osaxma** [supabase-community/supabase-flutter#87] opened 2022-01-19 14:02 UTC
Take the following function as an example:

```dart
  @override
  Future<void> markNotificationsAsSeen() async {
    final res = await supabaseClient
        .from('notifications')
        .update({'is_seen': true}, returning: ReturningOption.minimal)
        .eq('notified_uid', supabaseClient.auth.currentUser!.id)
        .eq('is_seen', false) // <~~~ commenting this out makes the error disappear
        .execute();
    if (res.hasError) {
      throw Exception(res.error);
    }
  }
```

When all `notifications` for the given `notified_uid` are already `false` (i.e. no result is returned), I get the following exception:

```
Exception: PostgrestError(message: [], code: null, details: null, hint: null)
``` 

I was able to confirm this in several ways:
- commenting out `.eq('is_seen', false)`  -- no issue
- Manually changing a single notification's `is_seen` to `false`  on Dashboard -- no issue on the first call, error appears in subsequent ones.
- I ran the query on the Dashboard -- no issues. 

Given that, I assume the error is caused when no results are returned. 

**Version**:
- supabase: `^0.2.13`
- flutter: `2.8.1`

**Comment by bdlukaa** [comment] 2022-07-16 20:51
Looks like an issue with `returning: ReturningOption.minimal`

**Comment by dshukertjr** [comment] 2022-09-30 08:17
The library now throws 404 error with message of `not found` now, which is the expected behavior of Postgrest when there are no rows to update, so closing this PR as it's resolved!

**Closed by dshukertjr** 2022-09-30 08:17 UTC
Labels: bug, postgrest

**Comment by JasonChiu-dev** [comment] 2022-12-23 06:44
> 
It is so strange to  throws 404 error with message of not found!!
On SQL command test, if the data is not found when doing "update" action,  the SQL response "Success. No rows returned". **It should not throws 404 error with message of not found.**

**Comment by JasonChiu-dev** [comment] 2022-12-23 07:07
> The library now throws 404 error with message of `not found` now, which is the expected behavior of Postgrest when there are no rows to update, so closing this PR as it's resolved!

It is so strange to throws 404 error with message of not found!!
On SQL command test, if the data is not found when doing "update" action, the SQL response "Success. No rows returned". It should not throws 404 error with message of not found.

For example, when I have the major table for the basic data (e.g. customers.customerId and customers.name) and then I have the relative table (orders) for the detail data (e.g. orders.numer, orders.customerId (foreign key relate to customer.customerId) ...) ...etc.

It is not necessary that I have to check table (orders) every time when I found I mis-typed the customers.customerId data and try to update customers table and orders table (maybe there were many records in orders table with the mis-typed the customers.customerId, or none record in orders table with the mis-typed the customers.customerId. But I just want to update the orders table when I update the customers table with the correct customers.customerId).

For your information.

Jason

**Comment by JasonChiu-dev** [comment] 2022-12-23 08:23
> It is so strange to throws 404 error with message of not found!! On SQL command test, if the data is not found when doing "update" action, the SQL response "Success. No rows returned". It should not throws 404 error with message of not found.
> 
> For example, when I have the major table for the basic data (e.g. customers.customerId and customers.name) and then I have the relative table (orders) for the detail data (e.g. orders.numer, orders.customerId (foreign key relate to customer.customerId) ...) ...etc.
> 
> It is not necessary that I have to check table (orders) every time when I found I mis-typed the customers.customerId data and try to update customers table and orders table (maybe there were many records in orders table with the mis-typed the customers.customerId, or there is none in orders table using the wrong customers.customerId. I just want to update the customer table with the correct customers.customerId and update the orders table at the same time, even if the wrong customers.customerId data has not been created in the orders table.)
> 
> It is not necessary to use the query command to check whether the data has been saved before modifying the data every time. This should be judged and processed by the SQL Update command.

It is so strange to throws 404 error with message of not found!!
On SQL command test, if the data is not found when doing "update" action, the SQL response "Success. No rows returned". It should not throws 404 error with message of not found.

For example, when I have the major table for the basic data (e.g. customers.customerId and customers.name) and then I have the relative table (orders) for the detail data (e.g. orders.numer, orders.customerId (foreign key relate to customer.customerId) ...) ...etc.

It is not necessary that I have to check table (orders) every time when I found I mis-typed the customers.customerId data and try to update customers table and orders table (maybe there were many records in orders table with the mis-typed the customers.customerId, or there is none in orders table using the wrong customers.customerId. I just want to update the customer table with the correct customers.customerId and update the orders table at the same time, even if the wrong customers.customerId data has not been created in the orders table.)

It is not necessary to use the query command to check whether the data has been saved before modifying the data every time. This should be judged and processed by the SQL Update command.

**Comment by JasonChiu-dev** [comment] 2022-12-23 08:24
> The library now throws 404 error with message of `not found` now, which is the expected behavior of Postgrest when there are no rows to update, so closing this PR as it's resolved!

It is so strange to throws 404 error with message of not found!!
On SQL command test, if the data is not found when doing "update" action, the SQL response "Success. No rows returned". It should not throws 404 error with message of not found.

For example, when I have the major table for the basic data (e.g. customers.customerId and customers.name) and then I have the relative table (orders) for the detail data (e.g. orders.numer, orders.customerId (foreign key relate to customer.customerId) ...) ...etc.

It is not necessary that I have to check table (orders) every time when I found I mis-typed the customers.customerId data and try to update customers table and orders table (maybe there were many records in orders table with the mis-typed the customers.customerId, or there is none in orders table using the wrong customers.customerId. I just want to update the customer table with the correct customers.customerId and update the orders table at the same time, even if the wrong customers.customerId data has not been created in the orders table.)

It is not necessary to use the query command to check whether the data has been saved before modifying the data every time. This should be judged and processed by the SQL Update command.
